
name: Build Navit Binarys for WinCE

on: [push, pull_request, workflow_dispatch]

jobs:
  build_wince:
    runs-on: ubuntu-latest
    container:
        image: ghcr.io/achimstuy/navit-wince:main
    steps:
      - uses: actions/checkout@v1
      - name: Prepare the WinCE build environment
        run: |
            bash scripts/setup_wince.sh
      - name: Build for Windows CE
        run: bash scripts/build_wince.sh
      - uses: actions/upload-artifact@v4
        with:
          path: wince/output
          name: WinCE Binary
